spring.application.name=programa-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/programa_db
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true